{
	{"Angels vs Devils", "Light or dark — pick your side!"},
	{"Back to School", "Uniforms, backpacks, and study-ready style!"},
	{"Beach Day", "Suns out, shades on, beach vibes!"},
	{"Boho Vibes", "Free-spirited with flowy layers!"},
	{"Business Chic", "Smart, sleek, and professional!"},
	{"Casual Day", "Simple, comfy, and effortlessly cool!"},
	{"Celebrity Lookalike", "Channel your inner superstar!"},
	{"Chic", "Effortless elegance with sleek, modern style!"},
	{"Country Chic", "Denim, boots, and rustic charm!"},
	{"Cosy Autumn", "Scarves, sweaters, and fall leaves!"},
	{"Cute and Cuddly", "Soft, plush, and adorable!"},
	{"Cyberpunk", "Neon, techwear, and city lights!"},
	{"Dark Fantasy", "Enchanted, eerie, and powerful!"},
	{"Dream Job", "Dress like the star of your dream career!"},
	{"Dreamy Pastels", "Soft colors and gentle vibes!"},
	{"Enchanted Evening", "Mystical glam with a touch of midnight magic!"},
	{"Enchanted Garden", "Blooming beauty and fairy dust!"},
	{"Fairycore", "Wings, sparkles, and magical forest charm!"},
	{"Fantasy Warrior", "Armor, magic, and heroic flair!"},
	{"Food", "Serve a look inspired by your favorite snack or meal!"},
	{"Futuristic", "Shiny metals, neon lights, and high-tech fashion!"},
	{"Galactic Glam", "Stars, shimmer, and cosmic chic!"},
	{"Garden Fairy", "Petals, wings, and floral grace!"},
	{"Golden Hour", "Warm tones and sunset glow!"},
	{"Gothic Glam", "Dark, mysterious, and beautifully edgy!"},
	{"Halloween", "Creepy, cute, or killer — bring the spooky vibes!"},
	{"Halloween Spook", "Creepy, cute, or scary fun!"},
	{"Haunted Doll", "Porcelain beauty with a spooky twist!"},
	{"Ice Queen", "Cold elegance and crystal sparkle!"},
	{"Magical Girl", "Cute, sparkly, and full of power!"},
	{"Masquerade Ball", "Masks, mystery, and elegance!"},
	{"Mystical Forest", "Elven charm and nature magic!"},
	{"Mythical Creature", "Dragons, sirens, or unicorns!"},
	{"Pop Star", "Stage-ready with shine and glam!"},
	{"Preppy Style", "Plaid skirts, polos, and neat vibes!"},
	{"Rainy Day", "Comfy, cozy, and cute under the drizzle!"},
	{"Red Carpet", "Walk the runway like a celebrity!"},
	{"Rockstar", "Bold outfits, cool shades, and stage energy!"},
	{"Royal Ball", "Elegant gowns and sparkling jewels!"},
	{"Royal Guard", "Strong, bold, and noble!"},
	{"Royal Rebel", "Mix royalty with attitude!"},
	{"Royal Wedding", "Glamorous gowns and regal suits!"},
	{"Royalty", "Dress like a king, queen, or noble!"},
	{"Slumber Party", "Pajamas, plushies, and cozy vibes!"},
	{"Space Explorer", "Futuristic suits and cosmic cool!"},
	{"Space Royalty", "Rule the galaxy with cosmic crowns and starlit glam!"},
	{"Sports Day", "Activewear and game-ready looks!"},
	{"Spring Picnic", "Pastels, flowers, and sunny smiles!"},
	{"Streetwear", "Trendy, cool, and confident!"},
	{"Summer Festival", "Colorful, bright, and full of energy!"},
	{"Sweet Like Candy", "Pastel treats and sugary looks!"},
	{"Tropical Paradise", "Bright florals and vacation mode!"},
	{"Under the Sea", "Mermaid magic and ocean dreams!"},
	{"Vaporwave Dream", "Retro pinks, purples, and digital chill vibes!"},
	{"Villain Vibes", "Dark elegance with attitude!"},
	{"Vintage Aesthetic", "Retro vibes from another era!"},
	{"Winter", "Cozy up in festive, frosty, or Christmasy fashion!"},
	{"Winter Formal", "Fancy, frosty, and glamorous!"},
	{"Winter Wonderland", "Cozy, snowy, and full of sparkle!"},
	{"Y2K", "Shiny gloss, bold colors, and early 2000s glam!"},
}
